-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Mitsumori.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import Mitsumori.Scalar exposing (defaultCodecs)


type alias BigInt =
    Mitsumori.Scalar.BigInt


type alias Cursor =
    Mitsumori.Scalar.Cursor


type alias Date =
    Mitsumori.Scalar.Date


type alias Datetime =
    Mitsumori.Scalar.Datetime


type alias Id =
    Mitsumori.Scalar.Id


type alias Json =
    Mitsumori.Scalar.Json


type alias Time =
    Mitsumori.Scalar.Time


type alias Uuid =
    Mitsumori.Scalar.Uuid


codecs : Mitsumori.Scalar.Codecs BigInt Cursor Date Datetime Id Json Time Uuid
codecs =
    Mitsumori.Scalar.defineCodecs
        { codecBigInt = defaultCodecs.codecBigInt
        , codecCursor = defaultCodecs.codecCursor
        , codecDate = defaultCodecs.codecDate
        , codecDatetime = defaultCodecs.codecDatetime
        , codecId = defaultCodecs.codecId
        , codecJson = defaultCodecs.codecJson
        , codecTime = defaultCodecs.codecTime
        , codecUuid = defaultCodecs.codecUuid
        }
