-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Mitsumori.Enum.OrderByDirection exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Defines a per-field sorting order

  - AscNullsFirst - Ascending order, nulls first
  - AscNullsLast - Ascending order, nulls last
  - DescNullsFirst - Descending order, nulls first
  - DescNullsLast - Descending order, nulls last

-}
type OrderByDirection
    = AscNullsFirst
    | AscNullsLast
    | DescNullsFirst
    | DescNullsLast


list : List OrderByDirection
list =
    [ AscNullsFirst, AscNullsLast, DescNullsFirst, DescNullsLast ]


decoder : Decoder OrderByDirection
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "AscNullsFirst" ->
                        Decode.succeed AscNullsFirst

                    "AscNullsLast" ->
                        Decode.succeed AscNullsLast

                    "DescNullsFirst" ->
                        Decode.succeed DescNullsFirst

                    "DescNullsLast" ->
                        Decode.succeed DescNullsLast

                    _ ->
                        Decode.fail ("Invalid OrderByDirection type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : OrderByDirection -> String
toString enum____ =
    case enum____ of
        AscNullsFirst ->
            "AscNullsFirst"

        AscNullsLast ->
            "AscNullsLast"

        DescNullsFirst ->
            "DescNullsFirst"

        DescNullsLast ->
            "DescNullsLast"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe OrderByDirection
fromString enumString____ =
    case enumString____ of
        "AscNullsFirst" ->
            Just AscNullsFirst

        "AscNullsLast" ->
            Just AscNullsLast

        "DescNullsFirst" ->
            Just DescNullsFirst

        "DescNullsLast" ->
            Just DescNullsLast

        _ ->
            Nothing
