-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MitsumoriApi.Object.Profile exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import MitsumoriApi.InputObject
import MitsumoriApi.Interface
import MitsumoriApi.Object
import MitsumoriApi.Scalar
import MitsumoriApi.Union
import ScalarCodecs


{-| Globally Unique Record Identifier
-}
nodeId : SelectionSet ScalarCodecs.Id MitsumoriApi.Object.Profile
nodeId =
    Object.selectionForField "ScalarCodecs.Id" "nodeId" [] (ScalarCodecs.codecs |> MitsumoriApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


id : SelectionSet ScalarCodecs.Uuid MitsumoriApi.Object.Profile
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (ScalarCodecs.codecs |> MitsumoriApi.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


created_at : SelectionSet ScalarCodecs.Datetime MitsumoriApi.Object.Profile
created_at =
    Object.selectionForField "ScalarCodecs.Datetime" "created_at" [] (ScalarCodecs.codecs |> MitsumoriApi.Scalar.unwrapCodecs |> .codecDatetime |> .decoder)


username : SelectionSet String MitsumoriApi.Object.Profile
username =
    Object.selectionForField "String" "username" [] Decode.string
