-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MitsumoriApi.Object.Quote_tags exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import MitsumoriApi.InputObject
import MitsumoriApi.Interface
import MitsumoriApi.Object
import MitsumoriApi.Scalar
import MitsumoriApi.ScalarCodecs
import MitsumoriApi.Union


text : SelectionSet String MitsumoriApi.Object.Quote_tags
text =
    Object.selectionForField "String" "text" [] Decode.string


quote_id : SelectionSet (Maybe MitsumoriApi.ScalarCodecs.Uuid) MitsumoriApi.Object.Quote_tags
quote_id =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "quote_id" [] (MitsumoriApi.ScalarCodecs.codecs |> MitsumoriApi.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


id : SelectionSet MitsumoriApi.ScalarCodecs.Uuid MitsumoriApi.Object.Quote_tags
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (MitsumoriApi.ScalarCodecs.codecs |> MitsumoriApi.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


quotes :
    SelectionSet decodesTo MitsumoriApi.Object.Quotes
    -> SelectionSet (Maybe decodesTo) MitsumoriApi.Object.Quote_tags
quotes object____ =
    Object.selectionForCompositeField "quotes" [] object____ (Basics.identity >> Decode.nullable)
