-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MitsumoriApi.Object.Quote_tagsConnection exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import MitsumoriApi.InputObject
import MitsumoriApi.Interface
import MitsumoriApi.Object
import MitsumoriApi.Scalar
import MitsumoriApi.ScalarCodecs
import MitsumoriApi.Union


edges :
    SelectionSet decodesTo MitsumoriApi.Object.Quote_tagsEdge
    -> SelectionSet (List decodesTo) MitsumoriApi.Object.Quote_tagsConnection
edges object____ =
    Object.selectionForCompositeField "edges" [] object____ (Basics.identity >> Decode.list)


pageInfo :
    SelectionSet decodesTo MitsumoriApi.Object.PageInfo
    -> SelectionSet decodesTo MitsumoriApi.Object.Quote_tagsConnection
pageInfo object____ =
    Object.selectionForCompositeField "pageInfo" [] object____ Basics.identity
