-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MitsumoriApi.Object exposing (..)


type PageInfo
    = PageInfo


type Profiles
    = Profiles


type ProfilesConnection
    = ProfilesConnection


type ProfilesDeleteResponse
    = ProfilesDeleteResponse


type ProfilesEdge
    = ProfilesEdge


type ProfilesInsertResponse
    = ProfilesInsertResponse


type ProfilesUpdateResponse
    = ProfilesUpdateResponse


type Quote_tags
    = Quote_tags


type Quote_tagsConnection
    = Quote_tagsConnection


type Quote_tagsDeleteResponse
    = Quote_tagsDeleteResponse


type Quote_tagsEdge
    = Quote_tagsEdge


type Quote_tagsInsertResponse
    = Quote_tagsInsertResponse


type Quote_tagsUpdateResponse
    = Quote_tagsUpdateResponse


type Quotes
    = Quotes


type QuotesConnection
    = QuotesConnection


type QuotesDeleteResponse
    = QuotesDeleteResponse


type QuotesEdge
    = QuotesEdge


type QuotesInsertResponse
    = QuotesInsertResponse


type QuotesUpdateResponse
    = QuotesUpdateResponse
