-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Mitsumori.Object.Quote_tags exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Mitsumori.InputObject
import Mitsumori.Interface
import Mitsumori.Object
import Mitsumori.Scalar
import Mitsumori.ScalarCodecs
import Mitsumori.Union


text : SelectionSet String Mitsumori.Object.Quote_tags
text =
    Object.selectionForField "String" "text" [] Decode.string


quote_id : SelectionSet (Maybe Mitsumori.ScalarCodecs.Uuid) Mitsumori.Object.Quote_tags
quote_id =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "quote_id" [] (Mitsumori.ScalarCodecs.codecs |> Mitsumori.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


id : SelectionSet Mitsumori.ScalarCodecs.Uuid Mitsumori.Object.Quote_tags
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (Mitsumori.ScalarCodecs.codecs |> Mitsumori.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


quotes :
    SelectionSet decodesTo Mitsumori.Object.Quotes
    -> SelectionSet (Maybe decodesTo) Mitsumori.Object.Quote_tags
quotes object____ =
    Object.selectionForCompositeField "quotes" [] object____ (Basics.identity >> Decode.nullable)
