-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Mitsumori.Object.QuotesEdge exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Mitsumori.InputObject
import Mitsumori.Interface
import Mitsumori.Object
import Mitsumori.Scalar
import Mitsumori.ScalarCodecs
import Mitsumori.Union


cursor : SelectionSet String Mitsumori.Object.QuotesEdge
cursor =
    Object.selectionForField "String" "cursor" [] Decode.string


node :
    SelectionSet decodesTo Mitsumori.Object.Quotes
    -> SelectionSet decodesTo Mitsumori.Object.QuotesEdge
node object____ =
    Object.selectionForCompositeField "node" [] object____ Basics.identity
